require('dotenv').config();
const { PORT, DB_URI, FRONTEND_URL, JWT_SECREATE, JWT_EXPIRESIN, SMPT_EMAIL_HOST, SMPT_EMAIL_PORT, SMPT_EMAIL_USER, SMPT_EMAIL_PASSWORD, SMPT_EMAIL_FROM, } = process?.env

module.exports = {
    PORT: PORT || 5522,
    DB_URI: DB_URI,
    FRONTEND_URL: FRONTEND_URL,
    JWT_SECREATE: JWT_SECREATE,
    JWT_EXPIRESIN: JWT_EXPIRESIN,

    SMPT_EMAIL_HOST: SMPT_EMAIL_HOST,
    SMPT_EMAIL_PORT: SMPT_EMAIL_PORT,
    SMPT_EMAIL_USER: SMPT_EMAIL_USER,
    SMPT_EMAIL_FROM: SMPT_EMAIL_FROM,
    SMPT_EMAIL_PASSWORD: SMPT_EMAIL_PASSWORD,
}